apiVersion: designate.openstack.org/v1beta1
kind: Designate
metadata:
  name: designate
  namespace: openstack
spec:
  secret: osp-secret
  serviceUser: designate
  customServiceConfig: |
    [DEFAULT]
    debug = true
  databaseInstance: openstack
  databaseUser: designate
  rabbitMqClusterName: rabbitmq
