apiVersion: designate.openstack.org/v1beta1
kind: DesignateWorker
metadata:
  name: designate-worker
spec:
  # TODO(user): Add fields here
  databaseInstance: openstack
  databaseUser: designate
  serviceUser: designate
  containerImage: quay.io/tripleowallabycentos9/openstack-designate-worker:current-tripleo
  enable: true
  serviceDescription: "Designate worker service"
  serviceName: designate-worker
  service_type: designate_worker
  replicas: 1
  secret: osp-secret
  customServiceConfig: |
    [DEFAULT]
    debug: true
  resources:
    requests:
      memory: "500Mi"
      cpu: "1.0"
